// src/utils/apartmentData.js
import { BedDouble, ShowerHead, Car, ChefHat, DoorOpen, Square as SquareIcon, Grid, Utensils, Shirt, Sofa, Layers } from 'lucide-react';

const apartmentData = {
  torre1: {
    'Tipología 1': {
      mainImage: '/images/tipologia01/02.webp',
      images: [
        { src: '/images/tipologia01/01.webp', alt: 'Tipología 1 - Vista 1' },
        { src: '/images/tipologia01/02.webp', alt: 'Tipología 1 - Vista 2' },
        { src: '/images/tipologia01/03.webp', alt: 'Tipología 1 - Vista 3' },
        { src: '/images/tipologia01/04.webp', alt: 'Tipología 1 - Vista 4' },
        { src: '/images/tipologia01/05.webp', alt: 'Tipología 1 - Vista 5' },
        { src: '/images/tipologia01/06.webp', alt: 'Tipología 1 - Vista 6' },
        { src: '/images/tipologia01/07.webp', alt: 'Tipología 1 - Vista 7' },
        { src: '/images/tipologia01/08.webp', alt: 'Tipología 1 - Vista 8' },
        { src: '/images/tipologia01/09.webp', alt: 'Tipología 1 - Vista 9' },
        { src: '/images/tipologia01/10.webp', alt: 'Tipología 1 - Vista 10' },
        { src: '/images/tipologia01/11.webp', alt: 'Tipología 1 - Vista 11' },
        { src: '/images/tipologia01/12.webp', alt: 'Tipología 1 - Vista 12' },
        { src: '/images/tipologia01/13.webp', alt: 'Tipología 1 - Vista 13' },
        { src: '/images/tipologia01/14.webp', alt: 'Tipología 1 - Vista 14' },
        { src: '/images/tipologia01/15.webp', alt: 'Tipología 1 - Vista 15' },
        { src: '/images/tipologia01/16.webp', alt: 'Tipología 1 - Vista 16' },
        { src: '/images/tipologia01/17.webp', alt: 'Tipología 1 - Vista 17' },
        { src: '/images/tipologia01/18.webp', alt: 'Tipología 1 - Vista 18' },
        { src: '/images/tipologia01/19.webp', alt: 'Tipología 1 - Vista 19' },
        { src: '/images/tipologia01/20.webp', alt: 'Tipología 1 - Vista 20' },
        { src: '/images/tipologia01/21.webp', alt: 'Tipología 1 - Vista 21' },
        { src: '/images/tipologia01/22.webp', alt: 'Tipología 1 - Vista 22' },
        { src: '/images/tipologia01/23.webp', alt: 'Tipología 1 - Vista 23' },
        { src: '/images/tipologia01/24.webp', alt: 'Tipología 1 - Vista 24' },
        { src: '/images/tipologia01/25.webp', alt: 'Tipología 1 - Vista 25' },
      ],
      description: 'La Tipología 01 de Alqantar Condominio ha sido diseñada en esquina, lo que le otorga mayor amplitud visual, luminosidad y privacidad. Concebida para quienes buscan una unidad exclusiva de dos dormitorios, combina la comodidad de espacios generosos con la calidez de un entorno natural único en Villa Warcalde. Con una superficie propia de 175 m², esta tipología integra ambientes funcionales y elegantes, que se prolongan hacia balcones concebidos para disfrutar del verde y las vistas abiertas en cada momento del día.',
      size: '275 m²',
      features: [
        { icon: BedDouble, value: '2', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Grid, value: '1', color: 'bg-gray-600', label: 'Vestidor en Suite' },
        { icon: ChefHat, value: '1', color: 'bg-gray-600', label: 'Cocina' },
        { icon: Sofa, value: '1', color: 'bg-gray-600', label: 'Estar/Comedor' },
        { icon: Shirt, value: '1', color: 'bg-gray-600', label: 'Lavadero' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: DoorOpen, value: '3', color: 'bg-gray-600', label: 'Balcones' },
        { icon: Layers, value: '1', color: 'bg-gray-600', label: 'Baulera' },
        { icon: SquareIcon, value: '275 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
      details: [
        '2 dormitorios con balcón propio: uno de ellos en suite con vestidor y el otro con placard. Ambos amoblamientos Johnson.',
        'Living comedor integrado, con puertas ventanas de aluminio con DVH, que conectan al balcón terraza con asador.',
        'Cocina moderna y equipada, con amoblamientos Johnson, anafe, horno y extractor.',
        'Espacio independiente destinado a lavadero, que aporta practicidad y organización al hogar.',
        '2 baños completos con terminaciones premium, más un toilette que independiza el área social de la privada.',
        'Sistema de climatización propio, con dos equipos de aire frío/calor centralizados, garantizando confort durante todo el año.',
        '2 cocheras subterráneas y 1 baulera privada incluidas.',
      ],
    },
    'Tipología 2': {
      mainImage: '/images/tipologia02/02.webp',
      images: [
        { src: '/images/tipologia02/01.webp', alt: 'Tipología 2 - Vista 1' },
        { src: '/images/tipologia02/02.webp', alt: 'Tipología 2 - Vista 2' },
        { src: '/images/tipologia02/03.webp', alt: 'Tipología 2 - Vista 3' },
        { src: '/images/tipologia02/04.webp', alt: 'Tipología 2 - Vista 4' },
        { src: '/images/tipologia02/05.webp', alt: 'Tipología 2 - Vista 5' },
        { src: '/images/tipologia02/06.webp', alt: 'Tipología 2 - Vista 6' },
        { src: '/images/tipologia02/07.webp', alt: 'Tipología 2 - Vista 7' },
        { src: '/images/tipologia02/08.webp', alt: 'Tipología 2 - Vista 8' },
        { src: '/images/tipologia02/09.webp', alt: 'Tipología 2 - Vista 9' },
        { src: '/images/tipologia02/10.webp', alt: 'Tipología 2 - Vista 10' },
        { src: '/images/tipologia02/11.webp', alt: 'Tipología 2 - Vista 11' },
        { src: '/images/tipologia02/12.webp', alt: 'Tipología 2 - Vista 12' },
        { src: '/images/tipologia02/13.webp', alt: 'Tipología 2 - Vista 13' },
        { src: '/images/tipologia02/14.webp', alt: 'Tipología 2 - Vista 14' },
        { src: '/images/tipologia02/15.webp', alt: 'Tipología 2 - Vista 15' },
        { src: '/images/tipologia02/16.webp', alt: 'Tipología 2 - Vista 16' },
        { src: '/images/tipologia02/17.webp', alt: 'Tipología 2 - Vista 17' },
        { src: '/images/tipologia02/18.webp', alt: 'Tipología 2 - Vista 18' },
        { src: '/images/tipologia02/19.webp', alt: 'Tipología 2 - Vista 19' },
        { src: '/images/tipologia02/20.webp', alt: 'Tipología 2 - Vista 20' },
        { src: '/images/tipologia02/21.webp', alt: 'Tipología 2 - Vista 21' },
        { src: '/images/tipologia02/22.webp', alt: 'Tipología 2 - Vista 22' },
        { src: '/images/tipologia02/23.webp', alt: 'Tipología 2 - Vista 23' },
        { src: '/images/tipologia02/24.webp', alt: 'Tipología 2 - Vista 24' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 25' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 26' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 27' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 28' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 29' },
        { src: '/images/tipologia02/25.webp', alt: 'Tipología 2 - Vista 30' },
      ],
      description: 'La Tipología 02 de Alqantar Condominio ha sido diseñada en esquina, ofreciendo mayor luminosidad, amplitud visual y privacidad. Pensada para quienes buscan una residencia de gran categoría, combina la comodidad de tres dormitorios con la calidez de un entorno natural único en Villa Warcalde. Con una superficie propia de 210 m², esta tipología se distingue por su distribución inteligente, que potencia la vida social y al mismo tiempo resguarda la intimidad de los espacios privados. Cada ambiente se prolonga hacia balcones concebidos para disfrutar del verde y de las vistas abiertas en cualquier momento del día.',
      size: '320 m²',
      features: [
        { icon: BedDouble, value: '3', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Grid, value: '1', color: 'bg-gray-600', label: 'Vestidor en Suite' },
        { icon: ChefHat, value: '1', color: 'bg-gray-600', label: 'Cocina' },
        { icon: Sofa, value: '1', color: 'bg-gray-600', label: 'Estar/Comedor' },
        { icon: Shirt, value: '1', color: 'bg-gray-600', label: 'Lavadero' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: DoorOpen, value: '4', color: 'bg-gray-600', label: 'Balcones' },
        { icon: Layers, value: '1', color: 'bg-gray-600', label: 'Baulera' },
        { icon: SquareIcon, value: '320 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
      details: [
        '3 dormitorios con balcón propio: la suite principal con vestidor, y los otros dos con placares. Todos los amoblamientos Johnson.',
        'Living comedor integrado, con puertas ventanas de aluminio con DVH, que conectan al balcón terraza con asador.',
        'Cocina moderna y equipada, con amoblamientos Johnson, anafe, horno y extractor.',
        'Espacio independiente destinado a lavadero, que aporta practicidad y organización al hogar.',
        '2 baños completos con terminaciones premium, más un toilette que independiza el área social de la privada.',
        'Sistema de climatización propio, con dos equipos de aire frío/calor centralizados, garantizando confort durante todo el año.',
        '2 cocheras subterráneas y 1 baulera privada incluidas.',
      ],
    },
    'Tipología 3': {
      mainImage: '/images/tipologia03/02.webp',
      images: [
        { src: '/images/tipologia03/01.webp', alt: 'Tipología 3 - Vista 1' },
        { src: '/images/tipologia03/02.webp', alt: 'Tipología 3 - Vista 2' },
        { src: '/images/tipologia03/03.webp', alt: 'Tipología 3 - Vista 3' },
        { src: '/images/tipologia03/04.webp', alt: 'Tipología 3 - Vista 4' },
        { src: '/images/tipologia03/05.webp', alt: 'Tipología 3 - Vista 5' },
        { src: '/images/tipologia03/06.webp', alt: 'Tipología 3 - Vista 6' },
        { src: '/images/tipologia03/07.webp', alt: 'Tipología 3 - Vista 7' },
        { src: '/images/tipologia03/08.webp', alt: 'Tipología 3 - Vista 8' },
        { src: '/images/tipologia03/09.webp', alt: 'Tipología 3 - Vista 9' },
        { src: '/images/tipologia03/10.webp', alt: 'Tipología 3 - Vista 10' },
        { src: '/images/tipologia03/11.webp', alt: 'Tipología 3 - Vista 11' },
        { src: '/images/tipologia03/12.webp', alt: 'Tipología 3 - Vista 12' },
        { src: '/images/tipologia03/13.webp', alt: 'Tipología 3 - Vista 13' },
        { src: '/images/tipologia03/14.webp', alt: 'Tipología 3 - Vista 14' },
        { src: '/images/tipologia03/15.webp', alt: 'Tipología 3 - Vista 15' },
        { src: '/images/tipologia03/16.webp', alt: 'Tipología 3 - Vista 16' },
        { src: '/images/tipologia03/17.webp', alt: 'Tipología 3 - Vista 17' },
      ],
      description: 'Perfecto equilibrio entre diseño y practicidad. Este apartamento de 2 dormitorios y 3 baños cuenta con 2 balcones estratégicamente ubicados que aportan luz natural y vistas privilegiadas. Con 2 cocheras y un asador privado, suma confort a su superficie de 265 m².',
      size: '265 m²',
      features: [
        { icon: BedDouble, value: '2', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Grid, value: '1', color: 'bg-gray-600', label: 'Vestidor en Suite' },
        { icon: ChefHat, value: '1', color: 'bg-gray-600', label: 'Cocina' },
        { icon: Sofa, value: '1', color: 'bg-gray-600', label: 'Estar/Comedor' },
        { icon: Shirt, value: '1', color: 'bg-gray-600', label: 'Lavadero' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: Layers, value: '1', color: 'bg-gray-600', label: 'Baulera' },
        { icon: DoorOpen, value: '2', color: 'bg-gray-600', label: 'Balcones' },
        { icon: SquareIcon, value: '265 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
      details: [
        '3 dormitorios con balcón propio: la suite principal con vestidor, y los otros dos con placares. Todos los amoblamientos Johnson.',
        'Living comedor integrado, con puertas ventanas de aluminio con DVH, que conectan al balcón terraza con asador.',
        'Cocina moderna y equipada, con amoblamientos Johnson, anafe, horno y extractor.',
        'Espacio independiente destinado a lavadero, que aporta practicidad y organización al hogar.',
        '2 baños completos con terminaciones premium, más un toilette que independiza el área social de la privada.',
        'Sistema de climatización propio, con dos equipos de aire frío/calor centralizados, garantizando confort durante todo el año.',
        '2 cocheras subterráneas y 1 baulera privada incluidas.',
      ],
    },
  },
};

export default apartmentData;