// src/utils/apartmentData.js
import { BedDouble, ShowerHead, Car, ChefHat, DoorOpen, Square as SquareIcon, Grid, Utensils, Shirt, Sofa, Layers } from 'lucide-react';

const apartmentData = {
  torre1: {
    'Tipología 1': {
      mainImage: '/images/tipologia01/02.png',
      images: [
        { src: '/images/tipologia01/01.jpg', alt: 'Tipología 1 - Vista 1' },
        { src: '/images/tipologia01/02.png', alt: 'Tipología 1 - Vista 2' },
        { src: '/images/tipologia01/03.png', alt: 'Tipología 1 - Vista 3' },
        { src: '/images/tipologia01/04.png', alt: 'Tipología 1 - Vista 4' },
        { src: '/images/tipologia01/05.png', alt: 'Tipología 1 - Vista 5' },
        { src: '/images/tipologia01/06.png', alt: 'Tipología 1 - Vista 6' },
        { src: '/images/tipologia01/07.png', alt: 'Tipología 1 - Vista 7' },
        { src: '/images/tipologia01/08.png', alt: 'Tipología 1 - Vista 8' },
        { src: '/images/tipologia01/09.png', alt: 'Tipología 1 - Vista 9' },
        { src: '/images/tipologia01/10.png', alt: 'Tipología 1 - Vista 10' },
        { src: '/images/tipologia01/11.png', alt: 'Tipología 1 - Vista 11' },
        { src: '/images/tipologia01/12.png', alt: 'Tipología 1 - Vista 12' },
        { src: '/images/tipologia01/13.png', alt: 'Tipología 1 - Vista 13' },
        { src: '/images/tipologia01/14.png', alt: 'Tipología 1 - Vista 14' },
        { src: '/images/tipologia01/15.png', alt: 'Tipología 1 - Vista 15' },
        { src: '/images/tipologia01/16.png', alt: 'Tipología 1 - Vista 16' },
        { src: '/images/tipologia01/17.png', alt: 'Tipología 1 - Vista 17' },
        { src: '/images/tipologia01/18.png', alt: 'Tipología 1 - Vista 18' },
        { src: '/images/tipologia01/19.png', alt: 'Tipología 1 - Vista 19' },
        { src: '/images/tipologia01/20.png', alt: 'Tipología 1 - Vista 20' },
        { src: '/images/tipologia01/21.png', alt: 'Tipología 1 - Vista 21' },
        { src: '/images/tipologia01/22.png', alt: 'Tipología 1 - Vista 22' },
        { src: '/images/tipologia01/23.png', alt: 'Tipología 1 - Vista 23' },
        { src: '/images/tipologia01/24.png', alt: 'Tipología 1 - Vista 24' },
        { src: '/images/tipologia01/25.png', alt: 'Tipología 1 - Vista 25' },
      ],
      description: 'La Tipología 01 de Alqantar Condominio ha sido diseñada en esquina, lo que le otorga mayor amplitud visual, luminosidad y privacidad. Concebida para quienes buscan una unidad exclusiva de dos dormitorios, combina la comodidad de espacios generosos con la calidez de un entorno natural único en Villa Warcalde. Con una superficie propia de 175 m², esta tipología integra ambientes funcionales y elegantes, que se prolongan hacia balcones concebidos para disfrutar del verde y las vistas abiertas en cada momento del día.',
      size: '275 m²',
      features: [
        { icon: BedDouble, value: '2', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Grid, value: '1', color: 'bg-gray-600', label: 'Vestidor en Suite' },
        { icon: ChefHat, value: '1', color: 'bg-gray-600', label: 'Cocina' },
        { icon: Sofa, value: '1', color: 'bg-gray-600', label: 'Estar/Comedor' },
        { icon: Shirt, value: '1', color: 'bg-gray-600', label: 'Lavadero' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: DoorOpen, value: '3', color: 'bg-gray-600', label: 'Balcones' },
        { icon: Layers, value: '1', color: 'bg-gray-600', label: 'Baulera' },
        { icon: SquareIcon, value: '275 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
      details: [
        '2 dormitorios con balcón propio: uno de ellos en suite con vestidor y el otro con placard. Ambos amoblamientos Johnson.',
        'Living comedor integrado, con puertas ventanas de aluminio con DVH, que conectan al balcón terraza con asador.',
        'Cocina moderna y equipada, con amoblamientos Johnson, anafe, horno y extractor.',
        'Espacio independiente destinado a lavadero, que aporta practicidad y organización al hogar.',
        '2 baños completos con terminaciones premium, más un toilette que independiza el área social de la privada.',
        'Sistema de climatización propio, con dos equipos de aire frío/calor centralizados, garantizando confort durante todo el año.',
        '2 cocheras subterráneas y 1 baulera privada incluidas.',
      ],
    },
    'Tipología 2': {
      mainImage: '/images/tipologia02/02.png',
      images: [
        { src: '/images/tipologia02/01.jpg', alt: 'Tipología 2 - Vista 1' },
        { src: '/images/tipologia02/02.png', alt: 'Tipología 2 - Vista 2' },
        { src: '/images/tipologia02/03.png', alt: 'Tipología 2 - Vista 3' },
        { src: '/images/tipologia02/04.png', alt: 'Tipología 2 - Vista 4' },
        { src: '/images/tipologia02/05.png', alt: 'Tipología 2 - Vista 5' },
        { src: '/images/tipologia02/06.png', alt: 'Tipología 2 - Vista 6' },
        { src: '/images/tipologia02/07.png', alt: 'Tipología 2 - Vista 7' },
        { src: '/images/tipologia02/08.png', alt: 'Tipología 2 - Vista 8' },
        { src: '/images/tipologia02/09.png', alt: 'Tipología 2 - Vista 9' },
        { src: '/images/tipologia02/10.png', alt: 'Tipología 2 - Vista 10' },
        { src: '/images/tipologia02/11.png', alt: 'Tipología 2 - Vista 11' },
        { src: '/images/tipologia02/12.png', alt: 'Tipología 2 - Vista 12' },
        { src: '/images/tipologia02/13.png', alt: 'Tipología 2 - Vista 13' },
        { src: '/images/tipologia02/14.png', alt: 'Tipología 2 - Vista 14' },
        { src: '/images/tipologia02/15.png', alt: 'Tipología 2 - Vista 15' },
        { src: '/images/tipologia02/16.png', alt: 'Tipología 2 - Vista 16' },
        { src: '/images/tipologia02/17.png', alt: 'Tipología 2 - Vista 17' },
        { src: '/images/tipologia02/18.png', alt: 'Tipología 2 - Vista 18' },
        { src: '/images/tipologia02/19.png', alt: 'Tipología 2 - Vista 19' },
        { src: '/images/tipologia02/20.png', alt: 'Tipología 2 - Vista 20' },
        { src: '/images/tipologia02/21.png', alt: 'Tipología 2 - Vista 21' },
        { src: '/images/tipologia02/22.png', alt: 'Tipología 2 - Vista 22' },
        { src: '/images/tipologia02/23.png', alt: 'Tipología 2 - Vista 23' },
        { src: '/images/tipologia02/24.png', alt: 'Tipología 2 - Vista 24' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 25' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 26' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 27' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 28' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 29' },
        { src: '/images/tipologia02/25.png', alt: 'Tipología 2 - Vista 30' },
      ],
      description: 'El lujo de los grandes espacios. Con 3 dormitorios luminosos y 3 baños, este apartamento combina amplitud con exclusividad. Sus 4 balcones panorámicos y su asador propio lo convierten en el lugar perfecto para quienes buscan un estilo de vida sofisticado. Incluye 2 cocheras y una superficie total de 320 m².',
      size: '320 m²',
      features: [
        { icon: BedDouble, value: '3', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: DoorOpen, value: '4', color: 'bg-gray-600', label: 'Balcones' },
        { icon: SquareIcon, value: '320 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
    },
    'Tipología 3': {
      mainImage: '/images/tipologia03/02.png',
      images: [
        { src: '/images/tipologia03/01.jpg', alt: 'Tipología 3 - Vista 1' },
        { src: '/images/tipologia03/02.png', alt: 'Tipología 3 - Vista 2' },
        { src: '/images/tipologia03/03.png', alt: 'Tipología 3 - Vista 3' },
        { src: '/images/tipologia03/04.png', alt: 'Tipología 3 - Vista 4' },
        { src: '/images/tipologia03/05.png', alt: 'Tipología 3 - Vista 5' },
        { src: '/images/tipologia03/06.png', alt: 'Tipología 3 - Vista 6' },
        { src: '/images/tipologia03/07.png', alt: 'Tipología 3 - Vista 7' },
        { src: '/images/tipologia03/08.png', alt: 'Tipología 3 - Vista 8' },
        { src: '/images/tipologia03/09.png', alt: 'Tipología 3 - Vista 9' },
        { src: '/images/tipologia03/10.png', alt: 'Tipología 3 - Vista 10' },
        { src: '/images/tipologia03/11.png', alt: 'Tipología 3 - Vista 11' },
        { src: '/images/tipologia03/12.png', alt: 'Tipología 3 - Vista 12' },
        { src: '/images/tipologia03/13.png', alt: 'Tipología 3 - Vista 13' },
        { src: '/images/tipologia03/14.png', alt: 'Tipología 3 - Vista 14' },
        { src: '/images/tipologia03/15.png', alt: 'Tipología 3 - Vista 15' },
        { src: '/images/tipologia03/16.png', alt: 'Tipología 3 - Vista 16' },
        { src: '/images/tipologia03/17.png', alt: 'Tipología 3 - Vista 17' },
      ],
      description: 'Perfecto equilibrio entre diseño y practicidad. Este apartamento de 2 dormitorios y 3 baños cuenta con 2 balcones estratégicamente ubicados que aportan luz natural y vistas privilegiadas. Con 2 cocheras y un asador privado, suma confort a su superficie de 265 m².',
      size: '265 m²',
      features: [
        { icon: BedDouble, value: '2', color: 'bg-gray-600', label: 'Dormitorios' },
        { icon: ShowerHead, value: '3', color: 'bg-gray-600', label: 'Baños' },
        { icon: Car, value: '2', color: 'bg-gray-600', label: 'Cocheras' },
        { icon: Utensils, value: '1', color: 'bg-gray-600', label: 'Asador' },
        { icon: DoorOpen, value: '2', color: 'bg-gray-600', label: 'Balcones' },
        { icon: SquareIcon, value: '265 m²', color: 'bg-gray-600', label: 'Superficie' },
      ],
    },
    // 'Terraza/Quincho': {
    //   mainImage: '/images/01.png',
    //   images: [
    //     { src: '/images/01.png', alt: 'Terraza/Quincho - Vista 1' },
    //     { src: '/images/02.png', alt: 'Terraza/Quincho - Vista 2' },
    //   ],
    //   description: 'Disfrutá momentos inolvidables en la terraza de Torre 1: un quincho exclusivo en altura, pensado para reuniones sociales, asados y encuentros rodeados de vistas espectaculares.',
    //   size: 'Común',
    //   features: [],
    // },
    // 'Subsuelo': {
    //   mainImage: '/images/01.png',
    //   images: [
    //     { src: '/images/01.png', alt: 'Subsuelo - Vista 1' },
    //     { src: '/images/02.png', alt: 'Subsuelo - Vista 2' },
    //   ],
    //   description: 'Sala de usos múltiples en el subsuelo de Torre 1.',
    //   size: 'Común',
    //   features: [],
    // },
  },
  // torre2: {
  //   'Tipología 1': {
  //     mainImage: '/images/04.png',
  //     images: [
  //       { src: '/images/04.png', alt: 'Tipología 1 - Vista 1' },
  //       { src: '/images/01.png', alt: 'Tipología 1 - Vista 2' },
  //     ],
  //     description: 'Apartamento en Torres VIP de diseño moderno.',
  //     size: 'N/A',
  //     features: [
  //       { icon: BedDouble, value: '1', color: 'bg-gray-600', label: 'Dormitorios' },
  //       { icon: ShowerHead, value: '1', color: 'bg-gray-600', label: 'Baños' },
  //       { icon: ChefHat, value: '1', color: 'bg-gray-600', label: 'Asador' },
  //       { icon: DoorOpen, value: '1', color: 'bg-gray-600', label: 'Balcones' },
  //       { icon: SquareIcon, value: 'N/A', color: 'bg-gray-600', label: 'Superficie' },
  //     ],
  //   },
  //   'Terraza/Quincho': {
  //     mainImage: '/images/01.png',
  //     images: [
  //       { src: '/images/01.png', alt: 'Terraza/Quincho - Vista 1' },
  //       { src: '/images/02.png', alt: 'Terraza/Quincho - Vista 2' },
  //     ],
  //     description: 'Terraza y quincho en la azotea de Torre 2.',
  //     size: 'Común',
  //     features: [],
  //   },
  //   'Subsuelo': {
  //     mainImage: '/images/01.png',
  //     images: [
  //       { src: '/images/01.png', alt: 'Subsuelo - Vista 1' },
  //       { src: '/images/02.png', alt: 'Subsuelo - Vista 2' },
  //     ],
  //     description: 'Sala de usos múltiples en el subsuelo de Torre 2.',
  //     size: 'Común',
  //     features: [],
  //   },
  // },
};

export default apartmentData;